type: php
docroot: dist
webserver_type: nginx-fpm
additional_hostnames: []
additional_fqdns: []
performance_mode: none
use_dns_when_possible: true
web_environment: []
nodejs_version: "18"

## This was meant to allow us to run ddev npm run dev - But it won't work.
web_extra_exposed_ports:
  - name: node-astro
    container_port: 4321
    http_port: 9998
    https_port: 9999

web_extra_daemons:
  - name: "astro"
    command: "npm run dev"
    directory: /var/www/html